Repository Toy2-team10/Talkhaja, pull requests merged in 2023-11, with the labels that each got.

#1 TALK-22--feat/layout/styles 공통 styles 파일 수정 및 추가
  styles/_mixin.scss
  styles/_variables.scss
  styles/index.scss
  styles/normalize.scss
Labels: design

#8 Feat: 채팅방 목록 조회 기능 구현
  apis/axios.ts
  apis/chatListAPI.ts
  pages/all-chat-list/chatList.module.scss
  pages/all-chat-list/index.tsx
  pages/my-chat-list/MyChatList.module.scss
  pages/my-chat-list/index.tsx
Labels: feature

#5 Talk 6 feat/chat 채팅페이지 구성
  .eslintrc.json
  apis/constant.ts
  components/chat/Chat.module.scss
  components/chat/LeftArrowIcon.tsx
  components/chat/MenuIcon.tsx
  components/chat/alert
  components/chat/container.tsx
  components/chat/header.tsx
  components/chat/mychat.tsx
  components/chat/otherchat.tsx
  next.config.js
  package-lock.json
  package.json
  pages/chat/Chat.module.scss
  pages/chat/index.tsx
  pages/chat/types.ts
  styles/_mixin.scss
  tsconfig.json
Labels: design

#12 Feat: 회원가입 기능 구현
  .eslintrc.json
  apis/Auth.ts
  components/common/Modal.module.scss
  components/common/Modal.tsx
  components/signup/SignUpModal.module.scss
  components/signup/SignUpModal.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_document.tsx
  pages/api/apiController.ts
  pages/login/index.tsx
  pages/login/login.module.scss
  pages/signup/index.tsx
  pages/signup/signUp.module.scss
  public/images/i.ts
  public/images/logo.png
  styles/_mixin.scss
  tsconfig.json
  utils/firebaseConfig.ts
  utils/loginStorage.ts
Labels: feature

#16 Feat: 채팅방 목록 디자인 임시 적용 / 채팅방 생성, 참여 기능 구현
  @types/types.ts
  apis/chatListAPI.ts
  components/ChatList/CreateChat.tsx
  components/Navigation/Navigation.tsx
  next.config.js
  pages/all-chat-list/chatList.module.scss
  pages/all-chat-list/index.tsx
  pages/chat-list/ChatList.module.scss
  pages/chat-list/all.tsx
  pages/chat-list/my.tsx
  pages/my-chat-list/MyChatList.module.scss
  pages/my-chat-list/index.tsx
Labels: feature

#22 feat : 채팅방 소켓연동 코드 변경 및 디자인 변경
  components/chat/Chat.module.scss
  components/chat/LeftArrowIcon.tsx
  components/chat/MenuIcon.tsx
  components/chat/footer.tsx
  components/chat/header.tsx
  components/chat/otherchat.tsx
  package-lock.json
  pages/chat-list/all.tsx
  pages/chat/[chatId].tsx
Labels: feature

#23 Talk 2 feat/user/login
  @types/user.ts
  apis/Auth.ts
  apis/Jwtinterceptors.ts
  apis/axios.ts
  apis/etc.ts
  components/signup/SignUpModal.module.scss
  package-lock.json
  package.json
  pages/api/apiController.ts
  pages/login/index.tsx
  pages/login/login.module.scss
  pages/signup/index.tsx
  pages/signup/signUp.module.scss
  recoil/atoms/userIdState.ts
  styles/_mixin.scss
  utils/loginStorage.ts
Labels: feature

#25 Feat: 숙소와 채팅 기능 구현
  @types/types.ts
  components/host-list/HostDetailsModal.tsx
  pages/chat-list/ChatList.module.scss
  pages/chat-list/all.tsx
  pages/chat-list/my.tsx
Labels: feature

#33 Refactor: 숙소와 채팅이 존재하면 미생성 후 이동
  components/ChatList/CreateChat.tsx
  components/host-list/HostDetailsModal.tsx
  hooks/t.ts
  pages/chat-list/all.tsx
Labels: feature

#44 Talk 18 feat/chat/view join Feat: 채팅방 인원조회 기능 추가
  apis/chatAPI.ts
  components/chat/Chat.module.scss
  components/chat/header.tsx
  components/chat/otherchat.tsx
  pages/chat/[chatId].tsx
Labels: feature

#47 Refactor: 채팅 목록 최신순 정렬, Feat: 생성된 채팅 실시간 표시, 30초마다 목록 반복 요청 기능 구현
  apis/socket.ts
  hooks/useConnectServerSocket.tsx
  pages/chat-list/all.tsx
  pages/chat-list/my.tsx
  utils/chatList.ts
  utils/formattedTimeData.ts
Labels: feature

#60 Fix: 숙소 채팅 생성 오류 수정
  components/HostList/HostDetailsModal.tsx
Labels: bug

#64 fix : 채팅방 무한 호출 해결
  components/ChatList/MyChatListItem.tsx
  components/HostList/HostDetailsModal.tsx
  components/c.ts
  components/chat/otherchat.tsx
  components/signup/SignUpModal.tsx
  pages/chat-list/ChatList.module.scss
  pages/chat-list/all.tsx
  pages/chat-list/my.tsx
  pages/chat/[chatId].tsx
  tsconfig.json
Labels: refactor

#65 design: 채팅방 hover 스타일 추가
  components/ChatList/MyChatListItem.tsx
  pages/chat-list/ChatList.module.scss
  pages/chat-list/all.tsx
  styles/normalize.scss
Labels: design

#66 Design: 네비게이션 디자인 수정
  components/ChatList/AllChatListItem/AllChatListItem.module.scss
  components/ChatList/AllChatListItem/AllChatListItem.tsx
  components/ChatList/AllChatListItem/JudgeWrapper/JudgeWrapper.module.scss
  components/ChatList/AllChatListItem/JudgeWrapper/JudgeWrapper.tsx
  components/ChatList/ChatListModal.module.scss
  components/ChatList/ChatListModal.tsx
  components/ChatList/ChatListModal/ChatListModal.module.scss
  components/ChatList/ChatListModal/ChatListModal.tsx
  components/ChatList/CreateChatButton/CreateChatButton.module.scss
  components/ChatList/CreateChatButton/CreateChatButton.tsx
  components/ChatList/index.ts
  components/common/Header/Header.module.scss
  components/common/Header/Header.tsx
  components/common/Navigation/Navigation.module.scss
  components/common/Navigation/Navigation.tsx
  pages/_app.tsx
  pages/chat-list/ChatList.module.scss
  pages/chat-list/all.tsx
  pages/chat-list/my.tsx
  pages/index.tsx
Labels: design

#71 Fix: 에러 해결
  components/HostList/HostDetailsModal.tsx
  components/HostList/HostListItem.tsx
Labels: bug
